'use client';

import { ArrowLeft, Download, CheckCircle2, Circle } from 'lucide-react';
import { useRef } from 'react';

export default function CRMReportPage() {
  const reportRef = useRef(null);

  const reportData = {
    title: 'CRM Report — Loan Application Summary',
    reportDate: '08 November 2025',
    generatedBy: 'Masrut Skills CRM System',
    department: 'Loan Management',
    clientInfo: {
      name: 'Niharika Rastogi',
      age: '26 years',
      contact: '+91 9876543210',
      email: 'niharika.r@gmail.com',
      location: 'Masrut, UP, India'
    },
    loanDetails: {
      type: 'Business Loan',
      status: 'Approved',
      amountRequested: '₹5,00,000',
      proposedInterest: '9.25%',
      repaymentTerm: 'Medium-term (5 years)',
      applicationDate: '01 November 2025',
      approvalDate: '07 November 2025',
      creditScore: '675 (a)'
    },
    leadSource: {
      source: 'Website Form',
      leadDate: '01 November 2025',
      assignedTo: 'Rahul Mehta',
      followUpDate: '03 November 2025, 10:00 AM',
      priorityLevel: 'HIGH'
    },
    communicationLog: [
      {
        date: '4 Nov 2025',
        mode: 'Email',
        summary: 'Automated Acknowledgment sent'
      },
      {
        date: '5 Nov 2025',
        mode: 'Call',
        summary: 'No response',
        notes: 'Left a message document submission reminders. Will follow up via email within 24hrs.'
      },
      {
        date: '6 Nov 2025',
        mode: 'Email',
        summary: 'Documents received',
        notes: 'Client submitted all required documents via portal.'
      }
    ],
    verificationStatus: [
      {
        step: 'Identity Verification (KYC)',
        status: 'completed',
        remarks: 'Aadhaar and PAN verified'
      },
      {
        step: 'Business Registration',
        status: 'progress',
        remarks: 'Pending final approval'
      },
      {
        step: 'Credit Check',
        status: 'completed',
        remarks: 'Score:752'
      }
    ],
    feedback: {
      text: 'Client was well-informed about loan procedures and interested in flexible repayment and prepayment options. Expressed concern over the time required for final verification to be complete.'
    },
    nextSteps: [
      'Prepare sanction letter draft by 08 Nov 2025',
      'Schedule digital signing appointment.',
      'Update client via email once the file is forwarded to the loan officer.'
    ]
  };

  const handleDownloadPDF = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header - No print */}
      <div className="bg-linear-to-r from-blue-600 to-blue-700 p-4 flex items-center justify-between shadow-md print:hidden">
        <div className="flex items-center gap-3">
          <button 
            onClick={() => window.history.back()}
            className="text-white hover:bg-white/20 p-2 rounded-lg transition"
            aria-label="Go back"
          >
            <ArrowLeft size={20} />
          </button>
          <h1 className="text-white text-lg font-semibold">CRM Report</h1>
        </div>
        <button
          onClick={handleDownloadPDF}
          className="flex items-center gap-2 bg-white text-blue-700 px-4 py-2 rounded-lg font-semibold hover:bg-blue-50 transition text-sm"
        >
          <Download size={16} />
          <span className="hidden sm:inline">Download PDF</span>
        </button>
      </div>

      {/* Report Content */}
      <div className="max-w-6xl mx-auto p-3 sm:p-6 lg:p-8" ref={reportRef}>
        <div className="bg-white rounded-lg shadow-sm print:shadow-none print:rounded-none border border-gray-200">
          {/* Report Header */}
          <div className="border-b border-gray-200 p-4 sm:p-6">
            <h1 className="text-xl sm:text-2xl font-bold text-gray-900 mb-3">{reportData.title}</h1>
            <div className="flex flex-wrap gap-4 text-xs sm:text-sm text-gray-600">
              <span><span className="font-semibold">Report Date:</span> {reportData.reportDate}</span>
              <span><span className="font-semibold">Generated By:</span> {reportData.generatedBy}</span>
              <span><span className="font-semibold">Department:</span> {reportData.department}</span>
            </div>
          </div>

          {/* Report Body - Two Column Layout */}
          <div className="p-4 sm:p-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Left Column */}
              <div className="space-y-6">
                {/* Client Information */}
                <section>
                  <h2 className="text-base sm:text-lg font-bold text-gray-900 mb-3 pb-2 border-b border-gray-300">
                    Client Information
                  </h2>
                  <div className="space-y-2 text-sm">
                    <div className="grid grid-cols-2 gap-2">
                      <span className="text-gray-600 font-medium">Field</span>
                      <span className="text-gray-600 font-medium">Details</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Client Name</span>
                      <span className="text-gray-900 font-medium">{reportData.clientInfo.name}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Age/Gender</span>
                      <span className="text-gray-900">{reportData.clientInfo.age}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Contact</span>
                      <span className="text-gray-900">{reportData.clientInfo.contact}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Email</span>
                      <span className="text-gray-900 break-all">{reportData.clientInfo.email}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Location</span>
                      <span className="text-gray-900">{reportData.clientInfo.location}</span>
                    </div>
                  </div>
                </section>

                {/* Lead Source & Assignment */}
                <section>
                  <h2 className="text-base sm:text-lg font-bold text-gray-900 mb-3 pb-2 border-b border-gray-300">
                    Lead Source & Assignment
                  </h2>
                  <div className="space-y-2 text-sm">
                    <div className="grid grid-cols-2 gap-2">
                      <span className="text-gray-600 font-medium">Field</span>
                      <span className="text-gray-600 font-medium">Details</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Lead Source</span>
                      <span className="text-gray-900">{reportData.leadSource.source}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Lead Date</span>
                      <span className="text-gray-900">{reportData.leadSource.leadDate}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Assigned to</span>
                      <span className="text-gray-900">{reportData.leadSource.assignedTo}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Follow-up Date</span>
                      <span className="text-gray-900">{reportData.leadSource.followUpDate}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Priority Level</span>
                      <span className="text-gray-900">{reportData.leadSource.priorityLevel}</span>
                    </div>
                  </div>
                </section>

                {/* Verification Status */}
                <section>
                  <h2 className="text-base sm:text-lg font-bold text-gray-900 mb-3 pb-2 border-b border-gray-300">
                    Verification Status
                  </h2>
                  <div className="space-y-2 text-sm">
                    <div className="grid grid-cols-3 gap-2">
                      <span className="text-gray-600 font-medium">Step</span>
                      <span className="text-gray-600 font-medium">Status</span>
                      <span className="text-gray-600 font-medium">Remarks</span>
                    </div>
                    {reportData.verificationStatus.map((item, index) => (
                      <div key={index} className="grid grid-cols-3 gap-2 py-2 border-t border-gray-200 items-center">
                        <span className="text-gray-700">{item.step}</span>
                        <div className="flex items-center gap-1">
                          {item.status === 'completed' ? (
                            <>
                              <CheckCircle2 className="text-green-600" size={14} />
                              <span className="text-green-600 text-xs">Completed</span>
                            </>
                          ) : (
                            <>
                              <Circle className="text-yellow-600" size={14} />
                              <span className="text-yellow-600 text-xs">In Progress</span>
                            </>
                          )}
                        </div>
                        <span className="text-gray-900">{item.remarks}</span>
                      </div>
                    ))}
                  </div>
                </section>
              </div>

              {/* Right Column */}
              <div className="space-y-6">
                {/* Loan Details */}
                <section>
                  <h2 className="text-base sm:text-lg font-bold text-gray-900 mb-3 pb-2 border-b border-gray-300">
                    Loan Details
                  </h2>
                  <div className="space-y-2 text-sm">
                    <div className="grid grid-cols-2 gap-2">
                      <span className="text-gray-600 font-medium">Field</span>
                      <span className="text-gray-600 font-medium">Details</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Loan Type</span>
                      <span className="text-gray-900 font-medium">{reportData.loanDetails.type}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Application ID</span>
                      <span className="text-gray-900">{reportData.loanDetails.status}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Amount Requested</span>
                      <span className="text-gray-900">{reportData.loanDetails.amountRequested}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Interest</span>
                      <span className="text-gray-900">{reportData.loanDetails.proposedInterest}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Repayment Term</span>
                      <span className="text-gray-900">{reportData.loanDetails.repaymentTerm}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Application Date</span>
                      <span className="text-gray-900">{reportData.loanDetails.applicationDate}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Approval Date</span>
                      <span className="text-gray-900">{reportData.loanDetails.approvalDate}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 py-2 border-t border-gray-200">
                      <span className="text-gray-700">Credit/Sanction Status</span>
                      <span className="text-gray-900">{reportData.loanDetails.creditScore}</span>
                    </div>
                  </div>
                </section>

                {/* Communication Log */}
                <section>
                  <h2 className="text-base sm:text-lg font-bold text-gray-900 mb-3 pb-2 border-b border-gray-300">
                    Communication Log
                  </h2>
                  <div className="space-y-3">
                    <div className="grid grid-cols-4 gap-2 text-xs text-gray-600 font-medium">
                      <span>Date</span>
                      <span>Mode</span>
                      <span className="col-span-2">Notes/Summary</span>
                    </div>
                    {reportData.communicationLog.map((log, index) => (
                      <div key={index} className="border-t border-gray-200 pt-2">
                        <div className="grid grid-cols-4 gap-2 text-sm">
                          <span className="text-gray-900">{log.date}</span>
                          <span className="text-gray-900">{log.mode}</span>
                          <div className="col-span-2">
                            <p className="text-gray-900 mb-1">{log.summary}</p>
                            {log.notes && (
                              <p className="text-gray-600 text-xs">{log.notes}</p>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </section>

                {/* Feedback and Notes */}
                <section>
                  <h2 className="text-base sm:text-lg font-bold text-gray-900 mb-3 pb-2 border-b border-gray-300">
                    Feedback and Notes
                  </h2>
                  <div className="bg-blue-50 p-3 rounded text-sm text-gray-700 leading-relaxed">
                    {reportData.feedback.text}
                  </div>
                </section>

                {/* Next Steps */}
                <section>
                  <h2 className="text-base sm:text-lg font-bold text-gray-900 mb-3 pb-2 border-b border-gray-300">
                    Next Steps
                  </h2>
                  <ul className="space-y-2 text-sm text-gray-700">
                    {reportData.nextSteps.map((step, index) => (
                      <li key={index} className="flex items-start gap-2">
                        <span className="text-blue-600 font-bold">•</span>
                        <span>{step}</span>
                      </li>
                    ))}
                  </ul>
                </section>
              </div>
            </div>
          </div>

          {/* Download Button - Only visible on screen, not in print */}
          <div className="p-4 sm:p-6 border-t border-gray-200 print:hidden">
            <button
              onClick={handleDownloadPDF}
              className="w-full bg-linear-to-r from-purple-700 to-purple-800 text-white py-3 rounded-lg font-semibold hover:from-purple-800 hover:to-purple-900 transition shadow-md flex items-center justify-center gap-2"
            >
              <Download size={18} />
              Download PDF
            </button>
          </div>
        </div>
      </div>

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          body {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }
          
          .print\\:hidden {
            display: none !important;
          }
          
          .print\\:shadow-none {
            box-shadow: none !important;
          }
          
          .print\\:rounded-none {
            border-radius: 0 !important;
          }
          
          @page {
            margin: 0.5cm;
            size: A4;
          }
          
          * {
            break-inside: avoid;
          }
          
          section {
            page-break-inside: avoid;
          }
        }
      `}</style>
    </div>
  );
}